### ISSUE TITLE
having this issue while running server/migrations

### ISSUE THREAD

**Issue by merin31** [twn39/django-cloudmedia#1]
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rojan/Desktop/merin/TheVoiceAPI/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/rojan/Desktop/merin/TheVoiceAPI/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/rojan/Desktop/merin/TheVoiceAPI/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/rojan/Desktop/merin/TheVoiceAPI/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/rojan/Desktop/merin/TheVoiceAPI/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/rojan/Desktop/merin/TheVoiceAPI/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/rojan/Desktop/merin/TheVoiceAPI/venv/lib/python3.10/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/rojan/Desktop/merin/TheVoiceAPI/venv/lib/python3.10/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/home/rojan/Desktop/merin/TheVoiceAPI/venv/lib/python3.10/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/rojan/Desktop/merin/TheVoiceAPI/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rojan/Desktop/merin/TheVoiceAPI/venv/lib/python3.10/site-packages/cloudmedia/admin.py", line 9, in <module>
    class MediaAdmin(admin.ModelAdmin):
  File "/home/rojan/Desktop/merin/TheVoiceAPI/venv/lib/python3.10/site-packages/cloudmedia/admin.py", line 21, in MediaAdmin
    @admin.display(description=_('file name'))
AttributeError: module 'django.contrib.admin' has no attribute 'display'
```

**Comment by twn39** [comment]
@merin31  please make sure you use the latest version of django.
